### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Kyouka0w0** [Kyouka0w0/furima-29379#11]
URL
https://furima-29379.herokuapp.com/

Basic認証のIDとパスワード
neko
0000

出品者用のメールアドレスとパスワード
Aさん　aaa@a.a
パス　11111a

購入者用のメールアドレスとパスワード
Bさん　bbb@b.b
パス　11111a

購入用カードの番号・期限・セキュリティコード
4242424242424242
12/24
123

よろしくお願いしますー！！

**Comment by tcamp1234** [comment]
Kyouka0w0 さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
